# cheese
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cheese.1.gz
complete -c cheese -l wide -s w --description '.'
complete -c cheese -l device -s d --description '.'
complete -c cheese -l fullscreen -s f --description '.'
complete -c cheese -l help -s h --description '.'
complete -c cheese -l version -s v --description '.'

