# enca
# Autogenerated from man page /usr/share/man/man1/enca.1.gz
complete -c enca -l WORD --description '.'
complete -c enca -s v -l version --description 'Prints program version and list of features (see section FEATURES).'

