# enconv
# Autogenerated from man page /usr/share/man/man1/enconv.1.gz
complete -c enconv -l WORD --description '.'
complete -c enconv -s v -l version --description 'Prints program version and list of features (see section FEATURES).'

