# extractbb
# Autogenerated from man page /usr/share/man/man1/extractbb.1.gz
complete -c extractbb -s x --description 'Write output in dvipdfmx\'s ``xbb\'\' format (default), which is the same as tha…'

