# htdigest
# Autogenerated from man page /usr/lib/jvm/default/man/man1/htdigest.1.gz
complete -c htdigest -s c --description 'Create the passwdfile.  If passwdfile already exists, it is deleted first.'

