# hwsim
# Autogenerated from man page /usr/lib/jvm/default/man/man1/hwsim.1.gz
complete -c hwsim -l version -s v --description 'Show version number and exit.'
complete -c hwsim -l help -s h --description 'Show help message and exit.'

