# irdb-get
# Autogenerated from man page /usr/lib/jvm/default/man/man1/irdb-get.1.gz
complete -c irdb-get -s h -l help --description 'Print help message.'
complete -c irdb-get -s v -l version --description 'Print version info.'

