# kpseaccess
# Autogenerated from man page /usr/lib/jvm/default/man/man1/kpseaccess.1.gz
complete -c kpseaccess -l help --description 'Print help message and exit.'
complete -c kpseaccess -l version --description 'Print version information and exit.'

