# libvirtd
# Autogenerated from man page /usr/lib/jvm/default/man/man8/libvirtd.8.gz
complete -c libvirtd -s h -l help --description '.'
complete -c libvirtd -s d -l daemon --description '.'
complete -c libvirtd -s f -l config --description '.'
complete -c libvirtd -s l -l listen --description '.'
complete -c libvirtd -s p -l pid-file --description '.'
complete -c libvirtd -s t -l timeout --description '.'
complete -c libvirtd -s v -l verbose --description '.'
complete -c libvirtd -l version --description '.'
complete -c libvirtd -o rw-r--r-- --description '.'

