# modhex
# Autogenerated from man page /usr/lib/jvm/default/man/man1/modhex.1.gz
complete -c modhex -s d --description 'Decode data (the default is to encode data).'
complete -c modhex -s h --description 'Use hex encoding for all non-modhex data.'

