# nautilus-sendto
# Autogenerated from man page /usr/lib/jvm/default/man/man1/nautilus-sendto.1.gz
complete -c nautilus-sendto -s '?' -l help --description 'Show a help message listing all the options and their meanings.'

