# osinfo-query
# Autogenerated from man page /usr/lib/jvm/default/man/man1/osinfo-query.1.gz
complete -c osinfo-query -s s -l sort-key --description 'Set the data sorting key.  Defaults sorting the first column.'

