# pw-jack
# Autogenerated from man page /usr/lib/jvm/default/man/man1/pw-jack.1.gz
complete -c pw-jack -s h --description 'Show help.'
complete -c pw-jack -s r --description 'The name of the remote instance to connect to.'
complete -c pw-jack -s v --description 'Verbose operation.'

