# pw-pulse
# Autogenerated from man page /usr/lib/jvm/default/man/man1/pw-pulse.1.gz
complete -c pw-pulse -s h --description 'Show help.'
complete -c pw-pulse -s r --description 'The name of the remote instance to connect to.'
complete -c pw-pulse -s v --description 'Verbose operation.'

