# qemu-ga
# Autogenerated from man page /usr/lib/jvm/default/man/man8/qemu-ga.8.gz
complete -c qemu-ga -s m -l method --description 'Transport method: one of unix-listen, virtio-serial, or isa-serial, or vsock-…'
complete -c qemu-ga -s p -l path --description 'Device/socket path (the default for virtio-serial is /dev/virtio-ports/org.'
complete -c qemu-ga -s l -l logfile --description 'Set log file path (default is stderr).'
complete -c qemu-ga -s f -l pidfile --description 'Specify pid file (default is /var/run/qemu-ga. pid).'
complete -c qemu-ga -s F -l fsfreeze-hook --description 'Enable fsfreeze hook.'
complete -c qemu-ga -s t -l statedir --description 'Specify the directory to store state information (absolute paths only, defaul…'
complete -c qemu-ga -s v -l verbose --description 'Log extra debugging information.'
complete -c qemu-ga -s V -l version --description 'Print version information and exit.'
complete -c qemu-ga -s d -l daemon --description 'Daemonize after startup (detach from terminal).'
complete -c qemu-ga -s b -l blacklist --description 'Comma-separated list of RPCs to disable (no spaces, ? to list available RPCs).'
complete -c qemu-ga -s D -l dump-conf --description 'Dump the configuration in a format compatible with qemu-ga. conf and exit.'
complete -c qemu-ga -s h -l help --description 'Display this help and exit.'
complete -c qemu-ga -o 'F/var/run/fsfreezehook.sh' --description '.'

