# smbinfo
# Autogenerated from man page /usr/lib/jvm/default/man/man1/smbinfo.1.gz
complete -c smbinfo -s v --description 'Print version number and exit.'
complete -c smbinfo -s V --description 'Verbose output.'
complete -c smbinfo -s h --description 'Print help explaining the command line options.'

