# texdoctk
# Autogenerated from man page /usr/share/man/man1/texdoctk.1.gz
complete -c texdoctk -s a --description 'autoview: autostart viewer if a listbox contains only one item (this will fre…'
complete -c texdoctk -o '?-' --description 'which indicate in which part of the .'

