# unixcmd
# Autogenerated from man page /usr/lib/jvm/default/man/man1/unixcmd.1.gz
complete -c unixcmd -s s --description 'management socket path (default is /var/run/unixcmd).'
complete -c unixcmd -s f --description 'configuration path (default is /etc/unixcmd).'
complete -c unixcmd -s v --description 'run parse machine in debug mode.'

