# vde_cryptcab
# Autogenerated from man page /usr/lib/jvm/default/man/man1/vde_cryptcab.1.gz
complete -c vde_cryptcab -s p --description 'It is possible to decide which local udp port to use.'
complete -c vde_cryptcab -s c --description 'run vde_cryptcab in client mode, trying to connect to   host .'
complete -c vde_cryptcab -s s --description 'specify the UNIX socket to be used by local programs for joining the VDE.'
complete -c vde_cryptcab -s P --description 'if specified, vde_cryptcab will run in pre-shared key mode, instead of genera…'
complete -c vde_cryptcab -s x --description 'Disable symmetric key encryption.'
complete -c vde_cryptcab -s k --description 'Send periodic "keepalive" packets to avoid server timeouts.'
complete -c vde_cryptcab -s d --description 'Run as daemon.'
complete -c vde_cryptcab -s v --description 'Verbose.'

