# vde_plug
# Autogenerated from man page /usr/lib/jvm/default/man/man1/vde_plug.1.gz
complete -c vde_plug -s p --description 'It is possible to decide which port of the switch to use.'
complete -c vde_plug -s g --description 'group ownership of the communication socket.'
complete -c vde_plug -s m --description 'octal chmod like permissions for the comm sockets.'
complete -c vde_plug -o sock --description ') specify the directory which contains the UNIX socket to be used by local pr…'

