# vde_l3
# Autogenerated from man page /usr/lib/jvm/default/man/man1/vde_l3.1.gz
complete -c vde_l3 -s v --description 'Creates a virtual network interfaces on the vde_l3 box, with address ipaddres…'
complete -c vde_l3 -s r --description 'Specify a static route through gateway to reach hosts in target_network with …'
complete -c vde_l3 -s G --description 'Specify a default gateway, to be used whenever no static route  is defined fo…'
complete -c vde_l3 -s M --description 'the unix socket where the parameters (interfaces addresses, routes, etc.'

