# vdekvm
# Autogenerated from man page /usr/lib/jvm/default/man/man1/vdekvm.1.gz
complete -c vdekvm -l mod --description 'octalmode,  specify the mode for comm socket. br.'
complete -c vdekvm -o sock --description 'socketpath,  specify the UNIX socket to be used by local programs for joining…'
complete -c vdekvm -s h -o help -l help --description 'print a Usage help.  NOTE Qemu has changed its syntax for networking (cvs Nov.'

