# virtiofsd
# Autogenerated from man page /usr/lib/jvm/default/man/man1/virtiofsd.1.gz
complete -c virtiofsd -s h -l help --description 'Print help.'
complete -c virtiofsd -s V -l version --description 'Print version.'
complete -c virtiofsd -s d --description 'Enable debug output.'
complete -c virtiofsd -l syslog --description 'Print log messages to syslog instead of stderr.'
complete -c virtiofsd -s o --description 'NDENT 7. 0.'
complete -c virtiofsd -l socket-path --description 'Listen on vhost-user UNIX domain socket at PATH.'
complete -c virtiofsd -l fd --description 'Accept connections from vhost-user UNIX domain socket file descriptor FDNUM.'
complete -c virtiofsd -l thread-pool-size --description 'Restrict the number of worker threads per request queue to NUM.'
complete -c virtiofsd -l cache --description 'Select the desired trade-off between coherency and performance.'

