# virt-login-shell
# Autogenerated from man page /usr/lib/jvm/default/man/man1/virt-login-shell.1.gz
complete -c virt-login-shell -s c --description '.'
complete -c virt-login-shell -s h -l help --description '.'
complete -c virt-login-shell -s V -l version --description '.'

