# virtlockd
# Autogenerated from man page /usr/lib/jvm/default/man/man8/virtlockd.8.gz
complete -c virtlockd -s h -l help --description '.'
complete -c virtlockd -s d -l daemon --description '.'
complete -c virtlockd -s f -l config --description '.'
complete -c virtlockd -s t -l timeout --description '.'
complete -c virtlockd -s p -l pid-file --description '.'
complete -c virtlockd -s v -l verbose --description '.'
complete -c virtlockd -s V -l version --description '.'
complete -c virtlockd -o rw-r--r-- --description '.'

