# virtlogd
# Autogenerated from man page /usr/lib/jvm/default/man/man8/virtlogd.8.gz
complete -c virtlogd -s h -l help --description '.'
complete -c virtlogd -s d -l daemon --description '.'
complete -c virtlogd -s f -l config --description '.'
complete -c virtlogd -s t -l timeout --description '.'
complete -c virtlogd -s p -l pid-file --description '.'
complete -c virtlogd -s v -l verbose --description '.'
complete -c virtlogd -s V -l version --description '.'
complete -c virtlogd -o rw-r--r-- --description '.'

