# virt-qemu-run
# Autogenerated from man page /usr/lib/jvm/default/man/man1/virt-qemu-run.1.gz
complete -c virt-qemu-run -s h -l help --description '.'
complete -c virt-qemu-run -s v -l verbose --description '.'
complete -c virt-qemu-run -s r -l root --description '.'
complete -c virt-qemu-run -s s -l secret --description '.'

