# virt-admin
# Autogenerated from man page /usr/lib/jvm/default/man/man1/virt-admin.1.gz
complete -c virt-admin -s c -l connect --description '.'
complete -c virt-admin -s d -l debug --description '.'
complete -c virt-admin -s h -l help --description '.'
complete -c virt-admin -s l -l log --description '.'
complete -c virt-admin -s q -l quiet --description '.'
complete -c virt-admin -s v -l version --description '.'
complete -c virt-admin -s V --description '.'
complete -c virt-admin -l filters --description 'Define a new set of logging filters where multiple filters are delimited by s…'
complete -c virt-admin -l outputs --description 'Define a new set of logging outputs where multiple outputs are delimited by s…'
complete -c virt-admin -l min-workers --description '.'
complete -c virt-admin -l max-workers --description '.'
complete -c virt-admin -l priority-workers --description '.'
complete -c virt-admin -l max-clients --description '.'
complete -c virt-admin -l max-unauth-clients --description '.'

