# ykclient
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ykclient.1.gz
complete -c ykclient -l help --description 'Display this help screen.'
complete -c ykclient -l version --description 'Display version information.'
complete -c ykclient -l debug --description 'Print debugging information.'
complete -c ykclient -l url --description 'Validation service URL, for example, "https://api. yubico. com/wsapi/2.'
complete -c ykclient -l ca --description 'Path to directory containing Certificate Authoritity, e. g.'
complete -c ykclient -l cai --description 'Path to a file holding one or more certificated to verify the peer with.'
complete -c ykclient -l apikey --description 'API key for HMAC validation of request/response.'
complete -c ykclient -l proxy --description 'Connect to validation service through a proxy, e. g.'

