# ykinfo
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ykinfo.1.gz
complete -c ykinfo -s s --description 'get the serial number and output it.'
complete -c ykinfo -s m --description 'get the serial number and output it as modhex.'
complete -c ykinfo -o nkey --description 'read from the nth key found.'
complete -c ykinfo -s H --description 'get the serial number and output it as hex.'
complete -c ykinfo -s v --description 'get the version and output it.'
complete -c ykinfo -s t --description 'get the touch level and output it.'
complete -c ykinfo -s p --description 'get the programming sequence and output it.'
complete -c ykinfo -s 1 --description 'get the status of slot 1, 1 for programmed and 0 for empty.'
complete -c ykinfo -s 2 --description 'get the status of slot 2, 1 for programmed and 0 for empty.'
complete -c ykinfo -s a --description 'get all the information above.'
complete -c ykinfo -s c --description 'get YubiKey capability information.'
complete -c ykinfo -s q --description 'modifier, only show the relevant data from the YubiKey, no extra information.'
complete -c ykinfo -s V --description 'print tool version and exit.'

