
[[plugins]]
repo = 'ryanoasis/vim-devicons'


[[plugins]]
repo = 'dracula/vim'


[[plugins]]
repo = 'hardcoreplayers/dashboard-nvim'

[[plugins]]
repo = 'hardcoreplayers/vim-buffet'
on_event = ['BufReadPre','BufNewFile']

[[plugins]]
repo = 'hardcoreplayers/spaceline.vim'
hook_source = '''
	let g:spaceline_seperate_style= 'slant'
'''
